#controllers:
#    resource: ../../src/Controller/
#    type: annotation
#
#preview-controllers:
#    resource: ../../templates/
#    type: annotation
#
#kernel:
#    resource: ../../src/Kernel.php
#    type: annotation
